<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="payroll.workers" tests="8" time="80.375" ignored="0" failures="1" timestamp="19 Apr 2021 16:24:47 GMT" skipped="0" hostname="LAPTOP" errors="0">
  <testcase name="workerExpense" time="11.911" classname="payroll.workers"/>
  <testcase name="payslipdeductionhistory" time="4.794" classname="payroll.workers"/>
  <testcase name="workerRate" time="13.306" classname="payroll.workers"/>
  <testcase name="paysliphistory" time="5.886" classname="payroll.workers"/>
  <testcase name="searchWorker" time="4.438" classname="payroll.workers"/>
  <testcase name="createWorker" time="28.715" classname="payroll.workers">
    <failure type="java.lang.AssertionError" message="expected [Worker Bank details: PattimattamMatthay] but found [Worker Bank details: Pattimattam]">
      <![CDATA[java.lang.AssertionError: expected [Worker Bank details: PattimattamMatthay] but found [Worker Bank details: Pattimattam]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at common.Utility.hardAssert(Utility.java:121)
	at payroll.workers.createWorker(workers.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- createWorker -->
  <testcase name="bankDetails" time="6.337" classname="payroll.workers"/>
  <testcase name="paysliptimesheethistory" time="4.988" classname="payroll.workers"/>
</testsuite> <!-- payroll.workers -->
